# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'log_return']

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# Cell
#import all relevant libraries
#import all the relevant libraries
#import codecademylib3_seaborn
import pandas as pd
import pandas_datareader.data as web
import pandas_datareader.wb as wb
import numpy as np
from datetime import datetime

# Cell
#new function for log returns
def log_return(prices):
  np.log(prices / prices.shift(1))